### ISSUE TITLE
MODS files: Sync'ing between Github and Fedora

### ISSUE THREAD

**Issue by awisnicki** [livingstoneonline/MODS-files#1]
I've just put up a few new MODS files (Manuscript MODS only), so if you pull down this repo you'll be able to identify them by modification date. Please put these up into Fedora. I've created this ticket because we should develop a workflow for when I create new MODS files. How would you like to handle this? I'm happy to go through Github rather than loading MODS files into Agnes.

**Comment by nigelgbanks** [comment]
Github seems like a good way to do this, lets have this the central location for adding metadata.

**Comment by awisnicki** [comment]
Consider it confirmed. Whenever I add new MODS records, I'll send you a pull request. I won't do it this time, but note that I opened this issue by noting that there were a few new MODS records so please ingest those.
